### ISSUE TITLE
So much errors [BUG]

### ISSUE THREAD

**Issue by bobhenl** [limbo56/PlayerSettings#26]
**Describe the bug**
When I click on item frame, it spam to my console this message.

**To Reproduce**
When I click on banner, it sends me to the console this message.

**Expected behavior**
It probably shouldn't send message :D like this.

**Screenshots**
Error here:
`[17:28:44 ERROR]: Could not pass event PlayerInteractAtEntityEvent to PlayerSettings v5.0.3
java.lang.NullPointerException: null
at me.limbo56.playersettings.settings.SimpleSettingWatcher.getValue(SimpleSettingWatcher.java:33) ~[?:?]
at me.limbo56.playersettings.listeners.StackerSettingListener.onPlayerStack(StackerSettingListener.java:28) ~[?:?]
at com.destroystokyo.paper.event.executor.asm.generated.GeneratedEventExecutor33.execute(Unknown Source) ~[?:?]
at org.bukkit.plugin.EventExecutor.lambda$create$1(EventExecutor.java:69) ~[patched_1.15.2.jar:git-Paper-260]
at co.aikar.timings.TimedEventExecutor.execute(TimedEventExecutor.java:80) ~[patched_1.15.2.jar:git-Paper-260]
at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[patched_1.15.2.jar:git-Paper-260]
at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:607) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PlayerConnection.a(PlayerConnection.java:2029) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:51) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PacketPlayInUseEntity.a(PacketPlayInUseEntity.java:6) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.PlayerConnectionUtils.lambda$ensureMainThread$0(PlayerConnectionUtils.java:23) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.TickTask.run(SourceFile:18) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeTask(IAsyncTaskHandler.java:136) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandlerReentrant.executeTask(SourceFile:23) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.executeNext(IAsyncTaskHandler.java:109) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.ba(MinecraftServer.java:1093) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.executeNext(MinecraftServer.java:1086) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.IAsyncTaskHandler.awaitTasks(IAsyncTaskHandler.java:119) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.sleepForTick(MinecraftServer.java:1047) ~[patched_1.15.2.jar:git-Paper-260]
at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:962) ~[patched_1.15.2.jar:git-Paper-260]
at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

+ another error:
`[16:42:21] [Craft Scheduler Thread - 10/WARN]: [PlayerSettings] Plugin PlayerSettings v5.0.3 generated an exception while executing task 5545
java.lang.IllegalStateException: SettingUpdateEvent may only be triggered synchronously.
    at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:595) ~[patched_1.15.2.jar:git-Paper-260]
    at me.limbo56.playersettings.settings.SimpleSettingWatcher.setValue(SimpleSettingWatcher.java:44) ~[?:?]
    at me.limbo56.playersettings.database.tasks.LoadPlayerTask.run(LoadPlayerTask.java:36) ~[?:?]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftTask.run(CraftTask.java:84) ~[patched_1.15.2.jar:git-Paper-260]
    at org.bukkit.craftbukkit.v1_15_R1.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:54) ~[patched_1.15.2.jar:git-Paper-260]
    at com.destroystokyo.paper.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:22) ~[patched_1.15.2.jar:git-Paper-260]
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149) [?:1.8.0_242]
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624) [?:1.8.0_242]
    at java.lang.Thread.run(Thread.java:748) [?:1.8.0_242]`

**Server version**
Add here the output of running the "/ver" command on your server. Please copy the exact output.
Version: This server is running Paper version git-Paper-260 (MC: 1.15.2) (Implementing API version 1.15.2-R0.1-SNAPSHOT)

**Additional context**
Nothing to share.

**Comment by bobhenl** [comment]
@limbo56

**Comment by bobhenl** [comment]
@limbo56
