### ISSUE TITLE
[BUG] java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource

### ISSUE THREAD

**Issue by ghost** [limbo56/PlayerSettings#56]
**Describe the bug**

Plugin fails to load when data storage mode is set to MySQL.

**To Reproduce**

1. Enable MySQL in the settings with a configured database
2. Restart server

**Expected behavior**

Plugin loads normally and uses supplied MySQL database for data storage.

**Screenshots**

[16:05:12 INFO]: [PlayerSettings] Enabling PlayerSettings v6.3.4
[16:05:12 INFO]: [PlayerSettings] Loading libraries...
[16:05:12 INFO]: [PlayerSettings] Loading configuration files...
[16:05:12 INFO]: [PlayerSettings] Connecting data manager...
[16:05:12 ERROR]: Error occurred while enabling PlayerSettings v6.3.4 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
        at me.limbo56.playersettings.database.SQLSettingsDatabase.connect(SQLSettingsDatabase.java:30) ~[?:?]
        at me.limbo56.playersettings.PlayerSettings.registerSettingsDatabase(PlayerSettings.java:162) ~[?:?]
        at me.limbo56.playersettings.PlayerSettings.onEnable(PlayerSettings.java:86) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:321) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:332) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:393) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at java.lang.Thread.run(Thread.java:829) [?:?]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
        at java.net.URLClassLoader.findClass(URLClassLoader.java:476) ~[?:?]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:102) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:87) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:589) ~[?:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:522) ~[?:?]
        ... 15 more
[16:05:12 INFO]: [PlayerSettings] Disabling PlayerSettings v6.3.4
[16:05:12 INFO]: [PlayerSettings] Save all users...
[16:05:12 ERROR]: Error occurred while disabling PlayerSettings v6.3.4 (Is it up to date?)
java.lang.NullPointerException: null
        at me.limbo56.playersettings.PlayerSettings.onDisable(PlayerSettings.java:139) ~[?:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:323) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.plugin.java.JavaPluginLoader.disablePlugin(JavaPluginLoader.java:360) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:336) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:454) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.loadPlugin(CraftServer.java:393) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at org.bukkit.craftbukkit.v1_8_R3.CraftServer.enablePlugins(CraftServer.java:352) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.s(MinecraftServer.java:439) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.k(MinecraftServer.java:403) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.a(MinecraftServer.java:358) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.DedicatedServer.init(DedicatedServer.java:301) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.run(MinecraftServer.java:603) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at net.minecraft.server.v1_8_R3.MinecraftServer.lambda$spin$0(MinecraftServer.java:133) ~[patched_1.8.8.jar:git-PandaSpigot-110]
        at java.lang.Thread.run(Thread.java:829) [?:?]

**Server version**

[16:07:45 INFO]: This server is running PandaSpigot version git-PandaSpigot-110 (MC: 1.8.8) (Implementing API version 1.8.8-R0.1-SNAPSHOT) (Git: 098345f)
[16:07:45 INFO]: You are 1 version(s) behind!
Download the new version at https://github.com/hpfxd/PandaSpigot

**Additional context**

**Comment by limbo56** [comment]
Hello there! The issue might be a conflict with other plugins using `Hikari` for their database. To help you, please let me know the names of any other plugins you've installed on your server. With that information, I'll be able to identify which plugin is causing the conflict. While I cannot offer a definite solution right now, I will investigate more to determine if there are any possible fixes.

**Comment by ghost** [comment]
Full plugin list:
[15:16:12 INFO]: Plugins (29): LunarClient-API, PlaceholderAPI, LunarClient-Impl, spark, ServersNPC, JoinSlot, FastAsyncWorldEdit, BedWarsProxy, ViaVersion, EnderButt, LuckPerms, WorldEdit, PlayerSettings, ProtocolLib, Vault, LPC, SafeNET, GrimAC, GadgetsMenu, LPX, GameBox, Battleship, SuperLobby, GemCrush, Minesweeper, WhacAMole, LogicPuzzles, MP-GameBundle, 2048

From these, currently BedWarsProxy and LuckPerms are using a MySQL database, I'm unsure about Hikari usage.

I tried using SQLite storage which is also what I'm using right now, but the plugin gives errors when players log out:
```
[PlayerSettings] An exception occurred while saving user settings
java.sql.SQLException: unable to open database file
       at org.sqlite.DB.throwex(DB.java:370)
       at org.sqlite.DB.executeBatch(DB.java:302)
       at org.sqlite.PrepStmt.executeBatch(PrepStmt.java:93)
       at me.limbo56.playersettings.database.sql.SaveUsersTask.execute(SaveUsersTask.java:44)
       at me.limbo56.playersettings.database.SQLiteSettingsDatabase.saveSettingWatchers(SQLiteSettingsDatabase.java:64)
       at me.limbo56.playersettings.user.UserManager.saveUsers(UserManager.java:129)
       at me.limbo56.playersettings.user.UserManager.saveUser(UserManager.java:139)
       at me.limbo56.playersettings.listeners.PlayerListener.lambda$unloadPlayer$2(PlayerListener.java:111)
       at me.limbo56.playersettings.util.TaskChain.lambda$runAsyncChain$0(TaskChain.java:43)
       at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEachFrom(ConcurrentLinkedQueue.java:1037)
       at java.base/java.util.concurrent.ConcurrentLinkedQueue.forEach(ConcurrentLinkedQueue.java:1054)
       at me.limbo56.playersettings.util.TaskChain.runAsyncChain(TaskChain.java:43)
       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftTask.run(CraftTask.java:59)
       at org.bukkit.craftbukkit.v1_8_R3.scheduler.CraftAsyncTask.run(CraftAsyncTask.java:53)
       at org.github.paperspigot.ServerSchedulerReportingWrapper.run(ServerSchedulerReportingWrapper.java:23)
       at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
       at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
       at java.base/java.lang.Thread.run(Thread.java:829)
```

**Comment by limbo56** [comment]
@Robert9157 I tried a similar setup to yours but couldn't reproduce the error you encountered on my end. However, after reviewing the new stack trace you provided, I suspect the problem may be related to permissions. Could you please verify that the user running your server has read/write access allowed to the `PlayerSettings` directory in your plugins folder?

**Comment by ghost** [comment]
The server is run in a Pterodactyl container, and the Pterodactyl daemon ensures file permissions are correct upon each (re)start, so that shouldn't be a cause. After further research however I realized the SQLite exception might be due to the database file not having the table (which the config mentions is necessary to create beforehand), and I do not know how to prepare such an SQLite database.

Is there any possibility however of resolving the Hikari error and the original problem? For me, either save method would work.

**Comment by limbo56** [comment]
@Robert9157 Hmm, in that case, I will have to investigate the cause of the problem further. Regarding the database file not having a table, that shouldn't affect the plugin as it will create the table automatically if it doesn't exist. I believe the issue is likely related to the server's inability to read the database file or load the libraries (`Hikari`) at runtime. I will keep you updated here if I find a solution.

Here are a few things to try in the meanwhile:

### Database file permission issue: 
Although the server is running in a Pterodactyl container that ensures correct file permissions, there might still be a permission issue with the database file.

#### Solution: 
Verify the file permissions of the database file and ensure that the server has the necessary read and write permissions. Double-check the ownership and permissions of the file within the container.

-----

### Database file corrupted: 
The error java.sql.SQLException: unable to open the database file indicates that the database file might be corrupted or inaccessible.

#### Solution: 
Delete the database file inside the `PlayerSettings` folder and restart the server.

-----

### Database configuration issue: 
There might be an issue with the database configuration settings, such as an incorrect name.

#### Solution: 
Review the database configuration settings and make sure that the property `storage.database` matches the name of the file ending in `.db` in the `PlayerSettings` folder.

**Comment by ghost** [comment]
Thanks for your reply.
1. I do not have the knowledge to perform this.
2. The issue persists.
3. Inferred from the 2nd solution, a file with name `playersettings.db` was recreated in the process. The issue persists.

If it is of any help to you to resolve the issue, here is the newly created database file along with my config.yml: 
[playersettings.tar.gz](https://github.com/limbo56/PlayerSettings/files/12045196/playersettings.tar.gz)

**Comment by MissGamerz** [comment]
im also getting this

any updates on how to fix this


`[18:34:38 ERROR]: Error occurred while enabling PlayerSettings v6.3.3 (Is it up to date?)
java.lang.NoClassDefFoundError: com/zaxxer/hikari/HikariDataSource
        at me.limbo56.playersettings.database.SQLSettingsDatabase.connect(SQLSettingsDatabase.java:30) ~[PlayerSettings-6.3.3.jar:?]
        at me.limbo56.playersettings.PlayerSettings.registerSettingsDatabase(PlayerSettings.java:162) ~[PlayerSettings-6.3.3.jar:?]
        at me.limbo56.playersettings.PlayerSettings.onEnable(PlayerSettings.java:86) ~[PlayerSettings-6.3.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:189) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:137) ~[PluginManager.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:274) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[PluginManager.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2447) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java:2407) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]
Caused by: java.lang.ClassNotFoundException: com.zaxxer.hikari.HikariDataSource
        at org.bukkit.plugin.java.PluginClassLoader.loadClass0(PluginClassLoader.java:185) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.plugin.java.PluginClassLoader.loadClass(PluginClassLoader.java:152) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
        ... 36 more
[18:34:38 INFO]: [PlayerSettings] Disabling PlayerSettings v6.3.3
[18:34:38 INFO]: [PlayerSettings] Save all users...
[18:34:38 ERROR]: Error occurred (in the plugin loader) while disabling PlayerSettings v6.3.3 (Is it up to date?)
java.lang.NullPointerException: Cannot invoke "me.limbo56.playersettings.user.UserManager.saveAll()" because "this.userManager" is null
        at me.limbo56.playersettings.PlayerSettings.onDisable(PlayerSettings.java:139) ~[PlayerSettings-6.3.3.jar:?]
        at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:283) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.disablePlugin(PaperPluginInstanceManager.java:224) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.disablePlugin(PaperPluginManagerImpl.java:109) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.disablePlugin(SimplePluginManager.java:537) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:193) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.enablePlugin(PluginUtils.java:137) ~[PluginManager.jar:?]
        at net.lenni0451.spm.utils.PluginUtils.loadPlugin(PluginUtils.java:274) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.subs.Load_Sub.execute(Load_Sub.java:55) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.lambda$onCommand$0(PluginManager_Command.java:94) ~[PluginManager.jar:?]
        at net.lenni0451.spm.commands.PluginManager_Command.onCommand(PluginManager_Command.java:110) ~[PluginManager.jar:?]
        at org.bukkit.command.PluginCommand.execute(PluginCommand.java:45) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.command.SimpleCommandMap.dispatch(SimpleCommandMap.java:168) ~[purpur-api-1.20.1-R0.1-SNAPSHOT.jar:?]
        at org.bukkit.craftbukkit.v1_20_R1.CraftServer.dispatchCommand(CraftServer.java:1001) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at org.bukkit.craftbukkit.v1_20_R1.command.BukkitCommandWrapper.run(BukkitCommandWrapper.java:64) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at com.mojang.brigadier.CommandDispatcher.execute(CommandDispatcher.java:265) ~[purpur-1.20.1.jar:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:332) ~[?:?]
        at net.minecraft.commands.Commands.performCommand(Commands.java:316) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.performChatCommand(ServerGamePacketListenerImpl.java:2447) ~[?:?]
        at net.minecraft.server.network.ServerGamePacketListenerImpl.lambda$handleChatCommand$22(ServerGamePacketListenerImpl.java:2407) ~[?:?]
        at net.minecraft.util.thread.BlockableEventLoop.lambda$submitAsync$0(BlockableEventLoop.java:59) ~[?:?]
        at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[?:?]
        at net.minecraft.server.TickTask.run(TickTask.java:18) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.doRunTask(BlockableEventLoop.java:153) ~[?:?]
        at net.minecraft.util.thread.ReentrantBlockableEventLoop.doRunTask(ReentrantBlockableEventLoop.java:24) ~[?:?]
        at net.minecraft.server.MinecraftServer.doRunTask(MinecraftServer.java:1365) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.d(MinecraftServer.java:197) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.pollTask(BlockableEventLoop.java:126) ~[?:?]
        at net.minecraft.server.MinecraftServer.pollTaskInternal(MinecraftServer.java:1342) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.pollTask(MinecraftServer.java:1335) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.util.thread.BlockableEventLoop.managedBlock(BlockableEventLoop.java:136) ~[?:?]
        at net.minecraft.server.MinecraftServer.waitUntilNextTick(MinecraftServer.java:1313) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1201) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:322) ~[purpur-1.20.1.jar:git-Purpur-2062]
        at java.lang.Thread.run(Thread.java:833) ~[?:?]`

**Comment by limbo56** [comment]
Apologies for the wait. I've updated some dependencies that might have been the root of the issue. I'm going to attach a download link for the beta version with the fix. Please let me know if you are still experiencing the issue.

Make sure you remove the `lib` folder inside the `PlayerSettings` directory.

[Download Beta](https://github.com/limbo56/PlayerSettings/releases/download/6.3.5-beta.1/PlayerSettings-6.3.5-beta.1.jar)

**Comment by limbo56** [comment]
@Robert9157 @MissGamerz

Hello, I tested again on my end, and it seems like the error was still present. I managed to figure out that the bug is being caused by a problem when loading the dependencies (in this case Hikari) at runtime. The code I had previously was not relocating the dependencies correctly. I updated some of the logic that loads the dependencies and managed to fix the error. Here is the download link to the fixed version. 

Please remember to remove the `lib` folder inside the `PlayerSettings` directory before starting your server with this new version.

[Download Beta 2](https://github.com/limbo56/PlayerSettings/releases/download/6.3.5-beta.2/PlayerSettings-6.3.5-beta.2.jar)

**Comment by limbo56** [comment]
@Robert9157 @MissGamerz 

Hello again. After further investigation, I found that some errors were still being thrown, even after addressing the previous issue. I managed to fix those errors in the latest release. I'll provide a link to download the updated version once more. This issue should now be resolved. If you experience it again, please reopen this issue or create a new one.

Remember to remove the `lib` folder inside the `PlayerSettings` directory before starting your server with this new version.

[Download 6.3.5](https://github.com/limbo56/PlayerSettings/releases/download/6.3.5/PlayerSettings-6.3.5.jar)
